### ISSUE TITLE
Button "back" on result page not work

### ISSUE THREAD

**Issue by gouyang** [kubevirt/web-ui#50]
on "Create Virtual Machine" wizard, fill proper data and go through the the "result" page. Click "back" does nothing.

**Comment by lizsurette** [comment]
@suomiy has created a PR to allow disabling the Back and Cancel buttons from the results page since they don't make sense to allow once the VM has been created:
https://github.com/kubevirt/web-ui-components/issues/61

**Comment by jelkosz** [comment]
will be fixed once we will pull a version of pf-react with [this](https://github.com/patternfly/patternfly-react/pull/801) change. Leaving opened until then.

**Comment by rawagner** [comment]
fixed in 1.3.-9

**Comment by gouyang** [comment]
![chrome](https://user-images.githubusercontent.com/1418734/48062032-c4d2f280-e1fb-11e8-9727-0d926564ca62.png)

For this situation, I actually want to go back to change the VM name.

**Comment by gouyang** [comment]
![vm](https://user-images.githubusercontent.com/1418734/48062074-ef24b000-e1fb-11e8-9cfe-55a905e11420.png)

For this situation, I actually want to go back to change the VM name.

**Comment by jelkosz** [comment]
That is actually one bug and one feature request what you say :)
1: So, the bug is that the validation of the subdomain on frontend is not correct and it fails on server
2: the feature request is to allow to return from the "results" page if the submit to the server fails

can you please open those?

**Comment by gouyang** [comment]
The reopen button is not visible to me.

**Comment by lizsurette** [comment]
@andybraren - Would you mind thinking about how we could represent an error state here? We'd want to allow the user to go back and make changes, too.

**Comment by suomiy** [comment]
@andybraren 
We are validating frontend validations in each tab because it is easier to fix them in place.

So I think the step with `validating configurations`, should give the user more clue what is actually happenning. E.g. sending request/trying/attempting to create VM? Because the thing is that also `Please wait` does not uphold to the meaning. The VM will be created even if you close the window (the request is already in the backend).

Also I don't think you should have an option go back when the VM was successfully created. I know you may want to create similar VM again, but I think that is confusing.

**Comment by rawagner** [comment]
@andybraren @suomiy 
So the 1 screen is ok,
2. screen should say `Creating Virtual Machine` instead of `Validatin Configuration`
3. screen is ok. When VM cannot be created, we show error and allow user to do Back and edit.
4. screen should have Back button disabled as VM is already created

Am I right ?

**Comment by lizsurette** [comment]
> @andybraren @suomiy
> So the 1 screen is ok,
> 2. screen should say `Creating Virtual Machine` instead of `Validatin Configuration`
> 3. screen is ok. When VM cannot be created, we show error and allow user to go Back and edit.
> 4. screen should have Back button disabled as VM is already created

I'd agree with all of this - @andybraren thoughts?

**Comment by andybraren** [comment]
I agree as well. "Validating configuration" was a mislabel because, as @suomiy said, the VM creation process is what's really going on in the backend.

Here's an updated image with what we've discussed above. I also disabled the Cancel button in step 4, since at that point the process is already in motion and can't be "cancelled".

![review-step-button-behavior-revised](https://user-images.githubusercontent.com/9122899/48428516-2eda2300-e739-11e8-88a7-a8f68f174f7a.png)

I'm not familiar with how long VMs typically (or could) take to be created, but I notice that screen 2's buttons currently "trap" the user into either waiting for it to finish or clicking `Cancel`. Can users actually "cancel" the creation process halfway through? If not, maybe `Cancel` should be disabled in this screen and `Close` should be enabled (but not blue) as seen below. Thoughts on this?

![review-step-behavior-revised-andy](https://user-images.githubusercontent.com/9122899/48429352-f3405880-e73a-11e8-99a1-ca437d0222cf.png)

**Comment by lizsurette** [comment]
> If not, maybe `Cancel` should be disabled in this screen and `Close` should be enabled (but not blue) to allow them to escape, as seen below. Thoughts on this?

I think this is a great idea if the creation doesn't take too long. I especially like the idea of "Close" becoming a secondary button styling at this point since it's really not the main action we want to be calling out to the user yet.

**Comment by rawagner** [comment]
> > If not, maybe `Cancel` should be disabled in this screen and `Close` should be enabled (but not blue) to allow them to escape, as seen below. Thoughts on this?
> 
> I think this is a great idea if the creation doesn't take too long. I especially like the idea of "Close" becoming a secondary button styling at this point since it's really not the main action we want to be calling out to the user yet.

AFAIK we cannot cancel the request, so disabling Cancel & enabling Close as non-primary button sounds good to me
