### ISSUE TITLE
Add new image source - boot from PVC

### ISSUE THREAD

**Issue by rawagner** [kubevirt/web-ui#63]
Using[ CDI-upload](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/upload.md) user can prepare PVC with bootable disk. However UI does not support this use case yet. We have 4 image sources - PXE, URL, Registry and Template. Shouldn't we add PVC image source ?

@lizsurette any ideas ?

**Comment by lizsurette** [comment]
> @lizsurette any ideas ?

Yes, @andybraren, @matthewcarleton and I have been thinking a lot about this on the UX side! The latest thought is that maybe we should allow the user to choose the source "Image", select the Image from a dropdown (this assuming an admin has already uploaded an image), and the in the Storage section a bootable disk would be added to the list (which would be created and backed by a PVC). I think the main question is should we highlight that it's an Image (or something else) as the source rather than it being a PVC and try to hide the term PVC which will most likely be confusing. What do you think about something like this?

**Comment by rawagner** [comment]
That could work. I can identify PVCs which were used as CDI upload target by their annotattion `cdi.kubevirt.io/storage.upload.target`. So if `Image` source is chosen, i would show new dropdown with PVCs with `cdi.kubevirt.io/storage.upload.target` annotation.

**Comment by lizsurette** [comment]
@rawagner that would be very cool! I say we try it and see how it works... I think it would be nice to do something similar in the Storage section to what we did with PXE/Network where I guess in this case we would automatically add this PVC as a disk and mark it as the bootable one. Thoughts?

**Comment by rawagner** [comment]
fixed with https://github.com/kubevirt/web-ui-components/pull/241
